### ISSUE TITLE
Review0210

### ISSUE THREAD

**Issue by mufeili** [RecLusIve-F/P-GNN-dgl#2] opened 2022-02-10 07:48 UTC
Overall the implementation looks great to me. Below are some minor comments.

1. It might be better to let users perform an experiment for one dataset at a time and you can drop the support of `All` for the argument `dataset`.
2. You can use `choices=[...]` in `add_argument` to restrict the values to be passed.
3. `dest` in `add_argument` is not necessary if it is the same as the argument name.
4. A general principle for this kind of example is bias for simplicity as it is not for production purpose. For example, L117-118 in `main.py` may not be necessary.
5. I don't think we need both argument `cache_no` and `cache`. For example, if `cache` is not specified, then `args.cache` will be False. The same principle applies to arguments `gpu`, `cpu`, `cuda`, `multi`, `multi_no`, `rm_feature`, `rm_feature_no`, `permute`, `permute_no`, `feature_pre`, `feature_pre_no`, `dropout`, `dropout_no`.
6. It might be better to replace the argument `rm_feature` with argument `inductive` if possible.
7. Do we still need the try-except logic [here](https://github.com/RecLusIve-F/P-GNN-dgl/blob/master/dataset.py#L259) with `choices=` in `add_argument` for the dataset argument?
8. Why do you have "f" in L263, but not in L265 [here](https://github.com/RecLusIve-F/P-GNN-dgl/blob/master/dataset.py#L263)?
9. Is pickle the best way to store and load data in this case? Have you tried alternatives like NumPy's data format?
10. The argument of `use_cache` in `get_dataset` is a bit confusing. When will we not want to use the cached data?

**Comment by RecLusIve-F** [comment] 2022-02-10 16:50
The problem mentioned on 1 to 8 have fixed in pull requests #3 .
With regard to 9 and 10, pickle is a solution I referenced from the original implementation, and I think NumPy's data format could also be a reasonable approach. But I did not compare the two, because I think these stored data are meant to reproduce the current experiment, since the validation and test sets are split randomly in each experiment. In most cases we will not use the cached data.

**Closed as completed** 2022-02-10 16:50 UTC
